version: "2"

run:
  timeout: 5m
  tests: true
  issues-exit-code: 1

linters:
  enable:
    - revive
    - goimports
    - govet
    - staticcheck
    - errcheck
    - gocyclo
    - dupl
    - unused
