version: "2"

run:
  timeout: 5m
  tests: true
  issues-exit-code: 1

linters:
  enable:
    - revive
    - goimports
    - govet
    - staticcheck
    - errcheck
    - gocyclo
    - dupl
    - unused

linters-settings:
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  revive:
    ignore-generated-header: true
    severity: warning
  goimports:
    local-prefixes: github.com/tracium

exclude-rules:
  - path: "_test\\.go"
    linters:
      - errcheck
      - dupl
      - gocyclo
  - linters:
      - errcheck
    text: "Error return value of .((os\\.)?std(out|err)\\..*|.*Close|.*Flush|os\\.Remove(All)?|.*printf?|os\\.(Un)?Setenv). is not checked"
