version: "2"

run:
  timeout: 5m
  tests: true
  issues-exit-code: 1

  exclude-rules:
    - path: "_test\\.go"
      linters:
        - gomnd
        - gocyclo
        - errcheck
        - dupl
        - gosec

    - linters:
        - errcheck
      text: "Error return value of .((os\\.)?std(out|err)\\..*|.*Close|.*Flush|os\\.Remove(All)?|.*printf?|os\\.(Un)?Setenv). is not checked"

    - linters:
        - golint
      text: "func name will be used as test\\.Test.* by other packages, and that stutters; consider calling this"

    - linters:
        - govet
      text: "(possible misuse of unsafe.Pointer|should have signature)"

    - linters:
        - staticcheck
      text: "ineffective break statement. Did you mean to break out of the outer loop"

  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - exhaustive
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace

linters-settings:
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goimports:
    local-prefixes: github.com/tracium
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  golint:
    min-confidence: 0
  maligned:
    suggest-new: true
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 120
