// Package models - Custody Chain structures for digital evidence
package models

import (
	"time"
)

// CustodyChainEntry represents a complete digital evidence custody chain entry
// This is the standardized structure used across all forensic agents (Evidex, Bitex, Tracium)
type CustodyChainEntry struct {
	// Unique identifier for this custody chain entry (UUID v4)
	ID string `json:"id"`

	// Agent/Source identification
	// Identifies which forensic agent created this entry (evidex, bitex, tracium)
	AgentType string `json:"agent_type"`

	// Version of the agent that created this entry (e.g., "1.0.0")
	AgentVersion string `json:"agent_version"`

	// Hostname of the machine where the agent ran
	AgentHostname string `json:"agent_hostname"`

	// Username who executed the agent
	AgentUser string `json:"agent_user"`

	// Timestamps
	// UTC timestamp when evidence collection started
	StartTimestamp time.Time `json:"start_timestamp"`

	// UTC timestamp when evidence collection completed
	EndTimestamp time.Time `json:"end_timestamp"`

	// Duration of the collection process
	Duration string `json:"duration"`

	// Case correlation
	// Case identifier to correlate evidence across multiple sources
	CaseID string `json:"case_id"`

	// Optional investigator identifier or badge number
	InvestigatorID string `json:"investigator_id,omitempty"`

	// Hashes - Standardized cryptographic integrity verification
	// MD5 hash of the complete evidence package (for compatibility, not primary)
	MD5Hash string `json:"md5_hash"`

	// SHA1 hash of the complete evidence package (for legacy compatibility)
	SHA1Hash string `json:"sha1_hash"`

	// SHA256 hash of the complete evidence package (primary integrity check)
	SHA256Hash string `json:"sha256_hash"`

	// Metadata
	// Total size of evidence in bytes
	TotalSizeBytes int64 `json:"total_size_bytes"`

	// Total number of files/items collected
	ItemCount int `json:"item_count"`

	// Compression method used (if any): "none", "gzip", "zip", "tar.gz"
	CompressionMethod string `json:"compression_method"`

	// Logs - RFC 5424 compliant syslog entries
	// Array of RFC 5424 formatted log entries from the agent
	LogEntries []string `json:"log_entries"`

	// Commands - All commands executed during collection
	// Complete history of all commands run by the agent
	CommandHistory []CommandExecution `json:"command_history"`

	// Chain of Custody tracking
	// Complete history of evidence custody transfers
	CustodyHistory []CustodyTransfer `json:"custody_history"`

	// Processor integration
	// URL of the Processor server where data was sent
	ProcessorURL string `json:"processor_url,omitempty"`

	// Timestamp when data was sent to Processor
	ProcessorSentAt time.Time `json:"processor_sent_at,omitempty"`

	// Status of transmission to Processor: "pending", "sent", "failed"
	ProcessorStatus string `json:"processor_status"`

	// Error message if transmission failed
	ProcessorError string `json:"processor_error,omitempty"`

	// References
	// Reference to TimeAnalysis report ID (if generated by Processor)
	TimeAnalysisRef string `json:"time_analysis_ref,omitempty"`

	// Reference to forensic report ID (if generated by Processor)
	ReportRef string `json:"report_ref,omitempty"`

	// Additional metadata specific to the evidence type
	AdditionalMetadata map[string]interface{} `json:"additional_metadata,omitempty"`

	// System context at time of collection
	SystemContext *SystemContext `json:"system_context"`

	// Integrity verification
	// Indicates if integrity checks passed: "verified", "failed", "not_verified"
	IntegrityStatus string `json:"integrity_status"`

	// Detailed integrity verification results
	IntegrityDetails string `json:"integrity_details,omitempty"`
}

// CommandExecution represents a single command execution during evidence collection
type CommandExecution struct {
	// Unique identifier for this command execution
	ID string `json:"id"`

	// The command that was executed (e.g., "fls", "exiftool", "ffprobe")
	Command string `json:"command"`

	// Full command-line arguments passed to the command
	Arguments []string `json:"arguments"`

	// UTC timestamp when command started
	StartTime time.Time `json:"start_time"`

	// UTC timestamp when command completed
	EndTime time.Time `json:"end_time"`

	// Duration of command execution
	Duration string `json:"duration"`

	// Exit code returned by the command
	ExitCode int `json:"exit_code"`

	// Size of stdout output in bytes
	StdoutSize int `json:"stdout_size"`

	// Size of stderr output in bytes
	StderrSize int `json:"stderr_size"`

	// Error message if command failed
	ErrorMessage string `json:"error_message,omitempty"`

	// Working directory where command was executed
	WorkingDirectory string `json:"working_directory"`

	// Environment variables relevant to the command (filtered for security)
	Environment map[string]string `json:"environment,omitempty"`

	// Target file or resource the command operated on
	TargetResource string `json:"target_resource,omitempty"`

	// Result summary or key findings from the command
	ResultSummary string `json:"result_summary,omitempty"`
}

// CustodyTransfer represents a single custody transfer event in the chain
type CustodyTransfer struct {
	// Unique identifier for this transfer event
	ID string `json:"id"`

	// Timestamp when custody transfer occurred
	Timestamp time.Time `json:"timestamp"`

	// Type of action: "collected", "transmitted", "received", "processed", "archived", "analyzed"
	Action string `json:"action"`

	// Name of the person or system taking custody
	CustodianName string `json:"custodian_name"`

	// Role or title of the custodian (e.g., "forensic analyst", "evidence processor")
	CustodianRole string `json:"custodian_role"`

	// Digital signature or authentication token for the custodian
	CustodianSignature string `json:"custodian_signature,omitempty"`

	// Name of the person or system transferring custody
	FromCustodian string `json:"from_custodian,omitempty"`

	// Physical or logical location of the evidence
	Location string `json:"location"`

	// Detailed notes about this custody event
	Notes string `json:"notes,omitempty"`

	// Hash verification at time of transfer
	VerificationHash string `json:"verification_hash,omitempty"`

	// Status of verification: "verified", "failed", "not_performed"
	VerificationStatus string `json:"verification_status"`
}

// EvidenceHashes contains all standard hash algorithms for an evidence item
type EvidenceHashes struct {
	// MD5 hash (128-bit) - for compatibility with legacy systems
	MD5 string `json:"md5"`

	// SHA1 hash (160-bit) - for compatibility with legacy systems
	SHA1 string `json:"sha1"`

	// SHA256 hash (256-bit) - primary hash for evidence integrity
	SHA256 string `json:"sha256"`

	// Timestamp when hashes were calculated
	CalculatedAt time.Time `json:"calculated_at"`

	// Algorithm used for hash calculation
	Algorithm string `json:"algorithm"`
}

// TimelineEntry represents a single event in the forensic timeline
// Used for TimeAnalysis integration with Processor
type TimelineEntry struct {
	// Unique identifier for this timeline entry
	ID string `json:"id"`

	// Timestamp of the event (can be any relevant timestamp)
	Timestamp time.Time `json:"timestamp"`

	// Type of timestamp: "created", "modified", "accessed", "deleted", "executed", "transmitted"
	TimestampType string `json:"timestamp_type"`

	// Source of the event: "file_system", "browser_history", "command_history", "network", "registry"
	Source string `json:"source"`

	// Description of the event
	Description string `json:"description"`

	// Path or identifier of the artifact (file path, URL, registry key, etc.)
	ArtifactPath string `json:"artifact_path"`

	// Type of artifact: "file", "directory", "browser_record", "command", "network_connection"
	ArtifactType string `json:"artifact_type"`

	// User associated with the event
	User string `json:"user,omitempty"`

	// Process associated with the event
	Process string `json:"process,omitempty"`

	// Additional metadata for the event
	Metadata map[string]interface{} `json:"metadata,omitempty"`

	// Hash of the artifact (if applicable)
	Hash string `json:"hash,omitempty"`

	// Size of the artifact in bytes (if applicable)
	Size int64 `json:"size,omitempty"`
}

// ProcessorResponse represents the response from Processor after receiving evidence
type ProcessorResponse struct {
	// Unique identifier assigned by Processor
	ProcessorID string `json:"processor_id"`

	// Timestamp when Processor received the data
	ReceivedAt time.Time `json:"received_at"`

	// Status of processing: "received", "processing", "completed", "failed"
	Status string `json:"status"`

	// Message from Processor
	Message string `json:"message"`

	// URL to view the evidence in Processor UI
	ViewURL string `json:"view_url,omitempty"`

	// Reference to TimeAnalysis report (if generated)
	TimeAnalysisID string `json:"time_analysis_id,omitempty"`

	// Reference to forensic report (if generated)
	ReportID string `json:"report_id,omitempty"`

	// Any errors encountered during processing
	Errors []string `json:"errors,omitempty"`
}

// SystemContext represents system information at time of evidence collection
// This is referenced from models.go but defined here for clarity
type SystemContext struct {
	// System hostname
	Hostname string `json:"hostname"`

	// User running the forensic tool
	Username string `json:"username"`

	// Operating system name
	OperatingSystem string `json:"operating_system"`

	// OS version string
	OSVersion string `json:"os_version"`

	// CPU architecture (x86_64, arm64, etc.)
	Architecture string `json:"architecture"`

	// System timezone
	TimeZone string `json:"timezone"`

	// Local time at collection
	LocalTime time.Time `json:"local_time"`

	// UTC time at collection
	UTCTime time.Time `json:"utc_time"`

	// Version of the binary/agent
	BinaryVersion string `json:"binary_version"`

	// Path to the binary
	BinaryPath string `json:"binary_path"`

	// Hash of the binary itself
	BinaryHash string `json:"binary_hash"`

	// Working directory at time of execution
	WorkingDirectory string `json:"working_directory"`
}
